version: '3.1'

services:
  app:
    container_name: bookaro
    image: bookaro:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bookaro
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: pass123
    ports:
      - 9080:8080
  db:
    container_name: bookarodb
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: bookaro
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
    ports:
      - 7432:5432